[package]
name = "suz_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
rand = "0.9.1"
rayon = "1.10.0"
subsphere = "0.7.1"
soft_sphere = { version = "0.1.0", path = "../soft_sphere" }

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "soft_body"
harness = false
